name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_BUCKET_NAME: ${{ vars.AWS_BUCKET_NAME }}
  AWS_GITHUB_S3_ROLE_NAME: ${{ vars.AWS_GITHUB_S3_ROLE_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest # O puedes fijar una versión como '1.1.0'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build project
        run: bun run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_GITHUB_S3_ROLE_NAME }}
          role-session-name: GitHubActionsS3Deployment

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${{ env.AWS_BUCKET_NAME }} --delete